import '@trendmicro/react-buttons/dist/react-buttons.css';
import '@trendmicro/react-paginations/dist/react-paginations.css';
import Anchor from '@trendmicro/react-anchor';
import { Button } from '@trendmicro/react-buttons';
import Checkbox from '@trendmicro/react-checkbox';
import { TablePagination } from '@trendmicro/react-paginations';
import ensureArray from 'ensure-array';
import _concat from 'lodash/concat';
import _filter from 'lodash/filter';
import _get from 'lodash/get';
import _includes from 'lodash/includes';
import _orderBy from 'lodash/orderBy';
import { Fragment } from 'react';
import { Scrollbars } from 'react-custom-scrollbars';
import { FixedSizeList as ListTable } from 'react-window';
import FormGroup from './components/FormGroup';
import Text from './components/Text';
import Table, { TableHeader, TableBody, TableRow, TableCell } from '../src';

import Selection from './examples/Selection';
import Expand from './examples/Expand';

global._concat = _concat;
global._filter = _filter;
global._get = _get;
global._includes = _includes;
global._orderBy = _orderBy;
global.Anchor = Anchor;
global.Button = Button;
global.Checkbox = Checkbox;
global.ensureArray = ensureArray;
global.Fragment = Fragment;
global.FormGroup = FormGroup;
global.Scrollbars = Scrollbars;
global.ListTable = ListTable;
global.Table = Table;
global.TableCell = TableCell;
global.TableHeader = TableHeader;
global.TableBody = TableBody;
global.TableRow = TableRow;
global.TablePagination = TablePagination;
global.Text = Text;

global.SelectionTable = Selection;
global.ExpandTable = Expand;
